variables:
  VERSION_ID: '1.0.$CI_PIPELINE_ID'

deploy:
  image: electronuserland/electron-builder:wine
  stage: build
  environment: production
  before_script:
    - cd source/www
    - node -v
    - npm -v
    - yarn --version
    - yarn
    - yarn test:flow
  artifacts:
    paths:
      - $CI_PROJECT_DIR/source/www/dist/*.*
  script:
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - CI=false yarn build && GH_TOKEN=36aeee759e974840cbcd481e3ea8325216609d28 yarn dist
  only:
    - master
  tags:
    - docker
