version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.2.1
  working_directory: ~/workspace

jobs:
  clone_and_hash:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-project-metadata-{{ .Branch }}
            - v1-project-metadata-master

      - run:
          name: Initialize project metadata
          command: |
            mkdir -p .project-metadata
            touch .project-{www,landing}-hash

      - run:
          name: Hash projects
          command: |
            git log --pretty=format:'%H' -n 1 -- www > .project-www-hash.new
            git log --pretty=format:'%H' -n 1 -- landing > .project-landing-hash.new

      - run:
          name: Determine changed projects
          command: |
            if ! diff .project-www-hash{,.new} > /dev/null; then
              touch .project-metadata/.project-www-changed
            fi

            if ! diff .project-landing-hash{,.new} > /dev/null; then
              touch .project-metadata/.project-landing-changed
            fi

      - run:
          name: Set current project hashes
          command: |
            mv .project-www-hash{.new,}
            mv .project-landing-hash{.new,}

      - persist_to_workspace:
          root: .
          paths:
            - .project-metadata

      - save_cache:
          key: v1-project-metadata-{{ .Branch }}-{{ epoch }}
          paths:
            - .project-www-hash
            - .project-landing-hash

  www:
    docker:
      - image: electronuserland/electron-builder:wine
    working_directory: ~/workspace
    environment:
      BASH_ENV: ~/.bashrc
    steps:
      - checkout: { path: ~/workspace }
      - attach_workspace: { at: . }
      - run:
          name: Check whether project changed
          command: |
            if [ -e .project-metadata/.project-www-changed ]; then
              echo "let's do this"
            else
              echo "nothing to do"
            fi

      - run:
          name: Publish Exmedia
          command: mkdir /root/.nvm && bash .circleci/publish-exmedia.sh
          no_output_timeout: 20m

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - clone_and_hash
      - www:
          requires:
            - clone_and_hash
          filters:
            branches:
              only: master